### ISSUE TITLE
Turn link properties into an object

### ISSUE THREAD

**Issue by HadrienGardeur** [HadrienGardeur/webpub-manifest#1]
In EPUB 3.x, there's a long list of properties that can be applied either at a spine or manifest level.
A good number of them could be grouped up, for example:

- there are a number of properties about what's contained in a resource (`svg`, `mathml`, `scripted`, `remote-resources`, `xmp`, `onix`)
- and many more that are related to how a resource is rendered, such as the placement in a spread (`page-spread-left`, `page-spread-right`, `page-spread-center`), the orientation of the device (`orientation-auto`, `orientation-landscape`, `orientation-portrait`), how the content flows (`flow-auto`, `flow-paginated`, `flow-scrolled-continuous`, `flow-scrolled-doc`) or the nature of the resource (`layout-pre-paginated`, `layout-reflowable`)

A number of properties have nothing to do in properties in the first place (`nav`, `cover-image`) and should show up in `rel` instead.

Instead of adopting the same model for Web Publications, I'm proposing an object model that would look a bit like this:

```json
{
  "href": "lesson1.html",
  "type": "text/html",
  "properties": {
    "contains": ["svg", "mathml", "script"],
    "layout": "pre-paginated",
    "orientation": "portrait"
  }
}
```

This approach has several benefits:

- it limits the number of properties to approximately 6-7 elements instead of 20+ in EPUB 3.1
- it also makes it much easier for a reading system to interact consistently with properties in a link object, with a much more JSON friendly approach than space separated values
- it's also a better extensibility model, since we can extend both properties and values

**Comment by danielweck** [comment]
+1 for grouping properties / "meta" data about link items.

**Comment by danielweck** [comment]
+1 for using `rel` wherever suitable.

**Comment by danielweck** [comment]
Question: what is the acceptance threshold to elevate a generic property to a "first class" attribute on a link element? For example, `width` and `height` for images:
https://github.com/readium/readium-2/blob/develop/examples/manifest.json#L31
`{"rel": "cover", "href": "images/cover.jpg", "type": "image/jpeg", "height": 1253, "width": 797}`

**Comment by HadrienGardeur** [comment]
If a property is useful across a large number of different resource types, then it should be treated as a first class attribute IMO.

For instance `height` and `width` can be useful for any bitmap image or video format while `duration` can be useful for any audio or video format.

Most of the properties in EPUB are very specific and most of them are actually only useful for FXL documents. I'd also like to move some existing EPUB attributes to properties instead, this includes: `linear`, `fallback` and `media-overlay`.

**Comment by danielweck** [comment]
`duration` would be useful for media overlays too, then.

**Comment by HadrienGardeur** [comment]
Work in progress at https://github.com/HadrienGardeur/webpub-manifest/blob/master/properties.md

cc @danielweck

**Comment by danielweck** [comment]
I was going to say "where's the new `viewport` metadata property?"
( http://www.idpf.org/epub/301/spec/epub-publications.html#fxl-property-viewport )
...then I realised "oh, it's deprecated already" ;)
( http://www.idpf.org/epub/31/spec/epub-packages.html#fxl-property-viewport )

**Comment by danielweck** [comment]
@HadrienGardeur I would suggest rephrasing the description for `spread`:
"Suggested method for handling synthetic spreads for the linked resource."
as:
"Indicates the condition to be met for the linked resource to be rendered within a synthetic spread."
See:
http://www.idpf.org/epub/31/spec/epub-packages.html#fxl-property-spread
and
http://www.idpf.org/epub/31/spec/epub-packages.html#fxl-property-spread-overrides

**Comment by HadrienGardeur** [comment]
Done.

The `fallback` attribute is another candidate for this new Properties Object, but that's something I'd like to discuss on this week's call first.

**Comment by HadrienGardeur** [comment]
Also, I believe that a property to replace `encryption.xml` could be useful. This property could contain one (or more?) URI to identify how the resource is encrypted.

Here's an example:
```
{
  "href": "chapter1.html",
  "type": "text/html",
  "properties": [
    "encrypted": "http://readium.org/lcp#basic-profile"
  ]
}
```

We might need other encryption-related properties, such as the original size or the store/deflate info.

cc @danielweck @llemeurfr @rkwright

**Comment by HadrienGardeur** [comment]
opened issue #2 to handle encryption
